var N = null;var sourcesIndex = {};
sourcesIndex["aho_corasick"] = {"name":"","dirs":[{"name":"packed","dirs":[{"name":"teddy","files":["compile.rs","mod.rs","runtime.rs"]}],"files":["api.rs","mod.rs","pattern.rs","rabinkarp.rs","vector.rs"]}],"files":["ahocorasick.rs","automaton.rs","buffer.rs","byte_frequencies.rs","classes.rs","dfa.rs","error.rs","lib.rs","nfa.rs","prefilter.rs","state_id.rs"]};
sourcesIndex["aoc_2020"] = {"name":"","files":["main.rs"]};
sourcesIndex["day01"] = {"name":"","files":["main.rs"]};
sourcesIndex["day02"] = {"name":"","files":["main.rs"]};
sourcesIndex["day03"] = {"name":"","files":["main.rs"]};
sourcesIndex["day04"] = {"name":"","files":["main.rs","passport.rs"]};
sourcesIndex["day05"] = {"name":"","files":["main.rs"]};
sourcesIndex["day06"] = {"name":"","files":["main.rs"]};
sourcesIndex["day07"] = {"name":"","files":["main.rs"]};
sourcesIndex["day08"] = {"name":"","files":["main.rs","vm.rs"]};
sourcesIndex["day09"] = {"name":"","files":["main.rs"]};
sourcesIndex["day10"] = {"name":"","files":["main.rs"]};
sourcesIndex["day11"] = {"name":"","files":["main.rs","seating.rs"]};
sourcesIndex["day12"] = {"name":"","files":["main.rs","ship.rs"]};
sourcesIndex["day13"] = {"name":"","files":["main.rs"]};
sourcesIndex["day14"] = {"name":"","files":["main.rs","system.rs"]};
sourcesIndex["day15"] = {"name":"","files":["main.rs"]};
sourcesIndex["day16"] = {"name":"","files":["main.rs"]};
sourcesIndex["day17"] = {"name":"","files":["main.rs"]};
sourcesIndex["day18"] = {"name":"","files":["main.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["inline_lazy.rs","lib.rs"]};
sourcesIndex["memchr"] = {"name":"","dirs":[{"name":"x86","files":["avx.rs","mod.rs","sse2.rs"]}],"files":["fallback.rs","iter.rs","lib.rs","naive.rs"]};
sourcesIndex["regex"] = {"name":"","dirs":[{"name":"literal","files":["imp.rs","mod.rs"]}],"files":["backtrack.rs","cache.rs","compile.rs","dfa.rs","error.rs","exec.rs","expand.rs","find_byte.rs","freqs.rs","input.rs","lib.rs","pikevm.rs","prog.rs","re_builder.rs","re_bytes.rs","re_set.rs","re_trait.rs","re_unicode.rs","sparse.rs","utf8.rs"]};
sourcesIndex["regex_syntax"] = {"name":"","dirs":[{"name":"ast","files":["mod.rs","parse.rs","print.rs","visitor.rs"]},{"name":"hir","dirs":[{"name":"literal","files":["mod.rs"]}],"files":["interval.rs","mod.rs","print.rs","translate.rs","visitor.rs"]},{"name":"unicode_tables","files":["age.rs","case_folding_simple.rs","general_category.rs","grapheme_cluster_break.rs","mod.rs","perl_word.rs","property_bool.rs","property_names.rs","property_values.rs","script.rs","script_extension.rs","sentence_break.rs","word_break.rs"]}],"files":["either.rs","error.rs","lib.rs","parser.rs","unicode.rs","utf8.rs"]};
sourcesIndex["thread_local"] = {"name":"","files":["cached.rs","lib.rs","thread_id.rs","unreachable.rs"]};
createSourceSidebar();
